export const CART_ACTION_TYPES = {
    SET_SHOW_CART_DROPDOWN: 'SET_SHOW_CART_DROPDOWN',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    SET_CARTITEMS: 'SET_CARTITEMS',
    SET_CART_QUANTITY:'SET_CART_QUANTITY'
}