export const CART_ACTION_TYPES = {
    SET_SHOW_CART_DROPDOWN: 'cart/SET_SHOW_CART_DROPDOWN',
    ADD_ITEM_TO_CART: 'cart/ADD_ITEM_TO_CART',
    SET_CARTITEMS: 'cart/SET_CARTITEMS',
    SET_CART_QUANTITY:'cart/SET_CART_QUANTITY'
}